commit 932689474 on 20220204

diff --git a/au b/au
--- a/au
+++ b/au
@@ -1,31 +1,24 @@
 #!/usr/bin/env sh
 # Copyright 2017-2022 (c) all rights reserved by SDRausty, see LICENSE.
-# https://sdrausty.github.io/au  Contributors: frumpylava/Glow, Hax4us
 # $ dpkg --purge name.pkg; dpkg --install name.pkg  ## downgrades packages. 
-# An external microSD card path is preferred in order to save native space on device, change path /storage/emulated/0/Android/media/com.termux/txdebs to a microSDcard destination to save native space on device.
+# In order to save native space on device the path /storage/emulated/0/Android/data/com.termux/txdebs can be changed to a microSDcard destination.
+# https://sdrausty.github.io/au  Contributors: Glow/frumpylava, Hax4us
 ################################################################################
-_AUDIR_ () {
-[ -e /storage/emulated/0/Android/media/com.termux/txdebs ] || { cd /storage/emulated/0/Android/media/com.termux/ && mkdir -p txdebs ; } || printf '%s' "Please create directory '/storage/emulated/0/Android/media/com.termux/' in Android.  If an micro sdcard is being used, '/storage/1234-5678/Android/media/com.termux/' and similar can be used after modifying ${0##*/};  "
-}
-# update, upgrade and install packages or print message
-_AUGET_ () {
-{ apt update && apt -o APT::Keep-Downloaded-Packages="true" upgrade -y && apt -o APT::Keep-Downloaded-Packages="true" install $@ -y  && find /data/data/com.termux/cache/apt/archives/ -maxdepth 1 -type f -name "*.deb" -exec mv -f {} /storage/emulated/0/Android/media/com.termux/txdebs/ \; ; } || printf "\\n%s\\n\\n" "Something unexpected occured;  Please study the first lines of the error output, and run ${0##*/} again to install and auto update packages!" 
-}
+set -eu
+_AUDIR_ () { [ -e /storage/emulated/0/Android/data/com.termux/txdebs ] || { cd /storage/emulated/0/Android/data/com.termux/ && mkdir -p txdebs ; } || _PRIT_ printf '%s' "Please create directory '/storage/emulated/0/Android/data/com.termux/' in Android.  If an external micro sdcard is being used, '/storage/1234-5678/Android/{data,media}/com.termux/' can be used after modifying the path in the ${0##*/} command;  " ; }
+# update, upgrade and then install packages if any or print message
+_AUGET_ () { { apt update && apt -o APT::Keep-Downloaded-Packages="true" upgrade -y && apt -o APT::Keep-Downloaded-Packages="true" install "$@" -y  && find /data/data/com.termux/cache/apt/archives/ -maxdepth 1 -type f -name "*.deb" -exec mv -f {} /storage/emulated/0/Android/data/com.termux/txdebs/ \; ; } || printf "\\n%s\\n\\n" "Something unexpected occured;  Please study the first lines of the error output, and run ${0##*/} again to install and auto update packages!" ; }
 _PD_ () { _PRNT_ "Command '${0##*/}':  DONE" ; }
+_PRIT_ () { printf "%s" "$1" ; } # print message with no trialing newline
 _PRNT_ () { printf "%s\\n" "$1" ; } # print message with one trialing newline
 _PB_ () { _PRNT_ "Command '${0##*/}':  BEGUN... " ; }
-set -u
+set +e
 PVAR="$(ping -n 1 1.1.1.1 2>&1)"
 set -e
 if [ -n "${PVAR##*unreachable*}" ]
 then
-	_PB_
-	_AUDIR_
-	_AUGET_ "$@"
-	_PD_
+	_PB_ && _AUDIR_ && _AUGET_ "$@" && _PD_
 else
-	_PB_
-        printf '%s;  Please check your wireless connection and run %s again.  Exiting... ' "$PVAR" "'${0##*/}'"
-	_PD_
+	_PB_ && _PRIT_ "$PVAR;  Please check your wireless connection and run '${0##*/}' again.  Exiting..." && _PD_
 fi
-# au FE
+# SDRausty/au FE
